#!/bin/sh
# deps jq

# credit :
# https://github.com/mitchweaver/mmbar

# kde :
# https://store.kde.org/p/1166510 # command output widget

# gnome :
# https://extensions.gnome.org/extension/2932/executor/ # executor

export WEATHER_FORMAT='F' # C, F
export LOCATION='Los_Angeles'
export SEPARATOR=' | '
export ENABLED_MODULES=\
"""
weather
disk
memory
uptime
"""

get_cpu() {
    cache=/tmp/barcpu
    if [ ! -f $cache ] || [ "$(( $(date +"%s") - $(stat -c "%Y" "$cache") ))" -gt "60"  ]; then
        rm -rf $cache
        grep 'cpu ' /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5)} END {print usage "%"}' >> $cache && cat $cache
    else
        cat $cache
    fi
}

get_uptime() {
    echo ⏱️ $(uptime -p | grep -Eo '[[:digit:]]{1,3} \w' | tr -d ' ' | tr '\n' ' ')
}

get_disk() {
    cache=/tmp/bardisk
    if [ ! -f $cache ] || [ "$(( $(date +"%s") - $(stat -c "%Y" "$cache") ))" -gt "3600"  ]; then
        rm -rf $cache
        df -h "/home" | awk ' /[0-9]/ {print "🖴  " $3 "/" $2}' |  tr '[A-Z]' '[a-z]' >> $cache && cat $cache
    else
        cat $cache
    fi
}

get_memory() {
    cache=/tmp/barmemory
    if [ ! -f $cache ] || [ "$(( $(date +"%s") - $(stat -c "%Y" "$cache") ))" -gt "30"  ]; then
        rm -rf $cache
        echo 💻 $(free --mebi | sed -n '2{p;q}' | awk '{printf ("%2.2fg/%2.2fg\n", ( $3 / 1024), ($2 / 1024))}') >> $cache && cat $cache
    else
        cat $cache
    fi
}

get_weather() {
    cache=/tmp/barweather
    if [ ! -f $cache ] || [ "$(( $(date +"%s") - $(stat -c "%Y" "$cache") ))" -gt "1800" ]; then
		rm -rf $cache
        http=$(curl --fail -sL "https://wttr.in/$LOCATION?format=j1")
		if [ "$http" != '' ]; then 
		echo $http | echo "🌦️ $(jq -r ".current_condition | .[].temp_$WEATHER_FORMAT") °F" >> $cache && cat $cache;
		fi
    else
        cat $cache
    fi
}

main() {
    info=$(
    for module in $ENABLED_MODULES ; do
        output=$(eval "get_${module}")
        if [ "$output" ] ; then
            printf '%s%s' "$output" "$SEPARATOR"
        fi
    done
    )
    printf '%s\n' "${info%$SEPARATOR}"
}

main
