#!/bin/sh

export SEPARATOR=' | '
export ENABLED_MODULES=\
"""
weather
memory
disk
cpu
"""

get_cpu() {
    cache=/tmp/barcpu
    if [ ! -f $cache ] || [ "$(( $(date +"%s") - $(stat -c "%Y" "$cache") ))" -gt "60"  ]; then
        rm -rf $cache
        grep 'cpu ' /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5)} END {print usage "%"}' >> $cache && cat $cache
    else
        cat $cache
    fi
}

get_disk() {
    cache=/tmp/bardisk
    if [ ! -f $cache ] || [ "$(( $(date +"%s") - $(stat -c "%Y" "$cache") ))" -gt "3600"  ]; then
        rm -rf $cache
        df -h "/home" | awk ' /[0-9]/ {print $3 "/" $2}' |  tr '[A-Z]' '[a-z]' >> $cache && cat $cache
    else
        cat $cache
    fi
}

get_memory() {
    cache=/tmp/barmemory
    if [ ! -f $cache ] || [ "$(( $(date +"%s") - $(stat -c "%Y" "$cache") ))" -gt "30"  ]; then
        rm -rf $cache
        free --mebi | sed -n '2{p;q}' | awk '{printf ("%2.2fg/%2.2fg\n", ( $3 / 1024), ($2 / 1024))}' >> $cache && cat $cache
    else
        cat $cache
    fi
}

get_weather() {
    cache=/tmp/barweather
    if [ ! -f $cache ]; then
        curl -s http://wttr.in/\?wn0QT | grep -Eo "[[:digit:]]{1,3} °\b[FC]\b" >> $cache && cat $cache
    else
        cat $cache
    fi
}

main() {
    info=$(
    for module in $ENABLED_MODULES ; do
        output=$(eval "get_${module}")
        if [ "$output" ] ; then
            printf '%s%s' "$output" "$SEPARATOR"
        fi
    done
    )
    printf '%s\n' "${info%$SEPARATOR}"
}

main
