#!/bin/sh
# github.com/dylanaraps

checkexec() {
	command -v "$1" > /dev/null
}

pkgs() {
if checkexec brew; then echo "$(brew list | wc -l | tr -d ' ') "
elif checkexec apt; then echo "$(dpkg -l | wc -l) "
elif checkexec pacman; then echo "$(pacman -Q | wc -l) "
elif checkexec xbps-install; then echo "$(xbps-query -l | wc -l) "
elif checkexec dnf; then echo "$(sudo dnf list installed | wc -l) "
elif checkexec zypper; then echo "$(zypper packages --installed-only | wc -l) "
elif checkexec apk; then echo "$(apk list | wc -l) " ; fi
}


(read -r _ _ k _ </proc/version;IFS=. read -r s _ </proc/uptime;d=$((s/60/60/24));h=$((s/60/60%24));m=$((s/60%60));[ "$d" = 0 ]||u="$u ${d}d";[ "$h" = 0 ]||u=$u\ ${h}h;[ "$m" = 0 ]||u=$u\ ${m}m;. /etc/os-release;while IFS=: read -r a b;do b=${b%kB};case $a in MemT*)_=$((z+=b));_=$((y=b));; Shmem)_=$((z+=b));;MemF*|Buf*|Cac*|SR*)_=$((z-=b));esac;done </proc/meminfo;_=$((z/=1024));_=$((y/=1024));set -- /var/db/k*/ins*/*/;printf '%b\n' "
[34;1m    ___      [33m${USER:-$(id -un)}[m@[33;1m$(cat /etc/hostname)[m
[34;1m   ([37m.· [34m|     [31mos[m:     ${PRETTY_NAME:-?}
[34;1m   ([35m<> [34m|     [31mshell[m:  ${SHELL##*/}
[34;1m  / [37m__  [34m\\    [31mpkgs[m:   $(pkgs)
[34;1m ( [37m/  \\ [34m/|   [31muptime[m:${u:-0m}
[35;1m_[34m/\\ [37m__)[34m/[35m_[34m)   [31mmemory[m: ${z:-?}mb / ${y:-?}mb
[35;1m\/[34m-____[35m\/    [31mkernel[m: ${k}
") 2>/dev/null
