#!/bin/sh
# just some aliases.

if [ $# -eq 0 ]; then echo "gt [i, b, p, c, a, cl, o]" ; fi

case $1 in
	i) git init ;;
	b) git branch -M main ;;
	p) git push -u origin main ;;
	a) git add * ;;
	c) git commit -m "pushed $(date +%s)" ;;
	cl) git clone "$2" ;;
	o) git remote add origin "$2" ;;
esac
