#!/bin/sh
# deps yt-dlp

musicpath=$HOME/Music
videopath=$HOME/Videos

if [ $# -eq 0 ]; then 
    echo "yt [mp3, mp4]" 
fi

case "$1" in
mp3)
    yt-dlp  -x -i --sponsorblock-remove all --audio-format mp3 "$2" -4 -o $musicpath/'%(title)'s-$(cat /dev/urandom | tr -dc "[:alnum:]" | head -c4).'%(ext)'s

;;

mp4)
    yt-dlp "$2" -i --sponsorblock-remove all --format mp4 -4 -o $videopath/'%(title)'s-$(cat /dev/urandom | tr -dc "[:alnum:]" | head -c4).'%(ext)'s
;;
esac
